version: "3.5"
 
services:
    app:
        image: bref/php-81-fpm-dev:2
        ports: [ '8002:8000' ]
        volumes:
            - .:/var/task
        environment:
            HANDLER: public/index.php
            # Assets will be served from this directory
            DOCUMENT_ROOT: public
