#
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Example Bref function built using AWS SAM. 

Transform:
- AWS::Serverless-2016-10-31

Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/hello-world.php
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      CodeUri: .
      Description: A Lambda function that returns a static string.
      Layers:
        - arn:aws:lambda:us-west-2:534081306603:layer:php-83:13
      Policies:
        - AWSLambdaBasicExecutionRole
